version: '3.8'

services:
  # Serviço para o backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=movie_cat
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  # Serviço para o frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-vue
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

  # Serviço para o banco de dados MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_cat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
