services:
  # Serviço para o backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-laravel
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

  # Serviço para o frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-vue
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    environment:
      - VUE_APP_BACKEND_URL=http://backend-laravel:${BACKEND_PORT:-8000}
    depends_on:
      - backend

  # Serviço para o banco de dados MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
